Fix the issue of the error for '_port_map'
neutron-zvm-agent pop up error: 'zvmNeutronAgent' object has no attribute '_port_map'.
Add define and check before _port_map is used.

Change-Id: I658f7612439b5c4cff8f6f8345d7bade954e2f0f